name: FRC Crash Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  crash-test:
    runs-on: windows-latest  # Using Windows since that's what WPILib primarily supports

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: C++ Setup
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "vc_redist.x64.exe"
        Start-Process -FilePath "vc_redist.x64.exe" -ArgumentList "/install", "/quiet", "/norestart" -Wait
        
    - name: Permissions
      run: chmod +x gradlew
      shell: bash
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Setup sim
      run: ./gradlew simulateExternalJavaRelease
        
    - name: Run Test
      run: ./gradlew runCrashTest